// Auto-generated by RAudioGenerator
using UnityEngine;

public static partial class R
{
    public static class Audio
    {
        public static AudioClip ActiveItem;
        public static AudioClip BuyShopSound;
        public static AudioClip CardTaked;
        public static AudioClip DestroyItem;
        public static AudioClip MouseHoverLoot;
        public static AudioClip MyClickSound;
        public static AudioClip pennypickup;
        public static AudioClip PlayLootCard;
        public static AudioClip slotspawn0;
        public static AudioClip SmokeSound;
        public static AudioClip superholy;
        public static AudioClip TreasureGet;
        public static AudioClip TurnIntoItem;
        public static AudioClip Debuff;
        public static AudioClip Vamp_Gulp;
        public static AudioClip batterycharge;
        public static AudioClip Lia;
        public static AudioClip MouseClicked;
        public static AudioClip MouseInButton;
        public static AudioClip PanelIn;
        public static AudioClip PanelOut;
        public static AudioClip hitSound;
        public static AudioClip Hurt_grunt;
        public static AudioClip click;
        public static AudioClip click_2;
        public static AudioClip load;
        public static AudioClip misc_menu;
        public static AudioClip misc_menu_2;
        public static AudioClip misc_menu_4;
        public static AudioClip misc_sound;
        public static AudioClip negative;
        public static AudioClip negative_2;
        public static AudioClip positive;
        public static AudioClip save;
        public static AudioClip sharp_echo;
        public static AudioClip Wrong_Error;
    }

    public static void InitAudio()
    {
        Audio.ActiveItem = Resources.Load<AudioClip>("Audio/ActiveItem");
        Audio.BuyShopSound = Resources.Load<AudioClip>("Audio/BuyShopSound");
        Audio.CardTaked = Resources.Load<AudioClip>("Audio/CardTaked");
        Audio.DestroyItem = Resources.Load<AudioClip>("Audio/DestroyItem");
        Audio.MouseHoverLoot = Resources.Load<AudioClip>("Audio/MouseHoverLoot");
        Audio.MyClickSound = Resources.Load<AudioClip>("Audio/MyClickSound");
        Audio.pennypickup = Resources.Load<AudioClip>("Audio/pennypickup");
        Audio.PlayLootCard = Resources.Load<AudioClip>("Audio/PlayLootCard");
        Audio.slotspawn0 = Resources.Load<AudioClip>("Audio/slotspawn0");
        Audio.SmokeSound = Resources.Load<AudioClip>("Audio/SmokeSound");
        Audio.superholy = Resources.Load<AudioClip>("Audio/superholy");
        Audio.TreasureGet = Resources.Load<AudioClip>("Audio/TreasureGet");
        Audio.TurnIntoItem = Resources.Load<AudioClip>("Audio/TurnIntoItem");
        Audio.Debuff = Resources.Load<AudioClip>("Audio/Buff/Debuff");
        Audio.Vamp_Gulp = Resources.Load<AudioClip>("Audio/Buff/Vamp_Gulp");
        Audio.batterycharge = Resources.Load<AudioClip>("Audio/Charge/batterycharge");
        Audio.Lia = Resources.Load<AudioClip>("Audio/EngineSounds/Lia");
        Audio.MouseClicked = Resources.Load<AudioClip>("Audio/EngineSounds/MouseClicked");
        Audio.MouseInButton = Resources.Load<AudioClip>("Audio/EngineSounds/MouseInButton");
        Audio.PanelIn = Resources.Load<AudioClip>("Audio/EngineSounds/PanelIn");
        Audio.PanelOut = Resources.Load<AudioClip>("Audio/EngineSounds/PanelOut");
        Audio.hitSound = Resources.Load<AudioClip>("Audio/Hit/hitSound");
        Audio.Hurt_grunt = Resources.Load<AudioClip>("Audio/Hit/Hurt_grunt");
        Audio.click = Resources.Load<AudioClip>("Audio/EngineSounds/Bank/click");
        Audio.click_2 = Resources.Load<AudioClip>("Audio/EngineSounds/Bank/click_2");
        Audio.load = Resources.Load<AudioClip>("Audio/EngineSounds/Bank/load");
        Audio.misc_menu = Resources.Load<AudioClip>("Audio/EngineSounds/Bank/misc_menu");
        Audio.misc_menu_2 = Resources.Load<AudioClip>("Audio/EngineSounds/Bank/misc_menu_2");
        Audio.misc_menu_4 = Resources.Load<AudioClip>("Audio/EngineSounds/Bank/misc_menu_4");
        Audio.misc_sound = Resources.Load<AudioClip>("Audio/EngineSounds/Bank/misc_sound");
        Audio.negative = Resources.Load<AudioClip>("Audio/EngineSounds/Bank/negative");
        Audio.negative_2 = Resources.Load<AudioClip>("Audio/EngineSounds/Bank/negative_2");
        Audio.positive = Resources.Load<AudioClip>("Audio/EngineSounds/Bank/positive");
        Audio.save = Resources.Load<AudioClip>("Audio/EngineSounds/Bank/save");
        Audio.sharp_echo = Resources.Load<AudioClip>("Audio/EngineSounds/Bank/sharp_echo");
        Audio.Wrong_Error = Resources.Load<AudioClip>("Audio/EngineSounds/Bank/Wrong Error");
    }
}
